### ISSUE TITLE
Add Multiple build layer

### ISSUE THREAD

**Issue by IchikawaYukko** [IchikawaYukko/docker-BattlefieldVietnamDedicatedServer#6]
Split 3 layer:
bfv_linded only
  +Server Manager
     +Mods (EoD etc...)

Add Makefile for multi layer build.

**Comment by ervitis** [comment]
With this pull request, the dockerfile has three layers:
- bfv_linded layer
- Server manager setup
- Mods
You can build any image selecting the build tags you want

**Comment by IchikawaYukko** [comment]
Hi @ervitis , Thank you for your cool PR!
I'm sorry for merging too late.
